---

- name: set hostname
  hostname:
    name: "{{ inventory_hostname_short }}.{{ ipa_domain }}"

- name: set /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname_short }}.{{ ipa_domain }} {{ inventory_hostname }}"
    state: present

- name: enable Identity Management system module
  shell: "dnf -y module enable idm:DL1 && dnf distro-sync"
  args:
    warn: no

- name: install IPA packages
  dnf:
    name:
      - ipa-server
      - ipa-server-dns
