---

- name: import common tasks
  import_tasks: common.yml

- name: install IPA primary server
  command: |
    ipa-server-install --setup-dns \
    --realm={{ realm }} \
    --domain={{ domain }} \
    --ds-password={{ dm_password }} \
    --admin-password={{ admin_password }} \
    --hostname={{ inventory_hostname_short }}.{{ domain }} \
    --unattended \
    --mkhomedir \
    --setup-dns \
    --forwarder={{ forwarder_1 }} \
    --forwarder={{ forwarder_2 }}
